### ISSUE TITLE
Backwards incompatible changes in bibliography

### ISSUE THREAD

**Issue by vlasakm** [olsak/OpTeX#142]
I tried the new bib changes, and found that the sorting now sorts based on the name of the first author and then by the year of publication. This is perfect with `\nonumcitations`!

However, I am not sure what was the previous behavior. I can only confirm that the bibliography sorting is different than previously. Is this desirable? Should the new sorting be opt-in to keep backwards compatibility?

I am torn, because on one hand I like the new behavior, but on the other hand with new OpTeX version my document will suddenly be different.

I know that many changes can actually change the document, even just changes in hyphenation patterns or exceptions, and to make sure my document compiles exactly I would have to keep the same versions of all packages.

I am fine with whatever solution. Feel free to close the issue. I just wanted to point out the issue before a new version gets released.

**Comment by olsak** [comment]
I don't exactly know the rules used by Librarian for sorting. It uses not only the first author?

I don't plan to search a configuration which emulates the Librarian sorting. The Librarian package uses sorting by codes, not by letters of an alphabet. So, Olzin is sorted before Olšák which is bad. IMHO, the emulation of bad sorting is not good idea. But someone can suggest an OpTeX trick similar to trick 0113 in order to accept all authors in the sorting rule, not only first one. The macro `\_preparesortingA` should be re-defined.

**Comment by vlasakm** [comment]
As I say, I like the new sorting better, and don't dwell on backwards compatibility.

Thanks for reassuring that the new sort order is well defined (unlike the old one). As it also makes perfect sense, I am closing the issue.
