### ISSUE TITLE
Adding `\pgforeground` to the output routine

### ISSUE THREAD

**Issue by Udi-Fogiel** [olsak/OpTeX#163]
would it make sense to add a `\pgforeground` token list so that it would be possible to add material to the foreground of the page? I needed that for one of my document, and thought maybe others would like that feature as well.

**Comment by olsak** [comment]
I implement `\pgforeground` as OpTeX trick, see my commit. The reason is that there is no simple and conceptual solution and we want to have simple output routine. Next level would be layers implemented in output routine, but it is another story. I want to keep the output routine simple. Maybe I will add a few examples of other output routines.

**Comment by Udi-Fogiel** [comment]
> I implement `\pgforeground` as OpTeX trick, see my commit. 

Thanks!

>The reason is that there is no simple and conceptual solution and we want to have simple output routine.

That is probably the correct choice.
