### ISSUE TITLE
Phantom larger than real in subscript

### ISSUE THREAD

**Issue by cao-** [olsak/OpTeX#25]
```
\fontfam[garamond]

$$
\eqalign{
	&s_a(x) \cr
	&s_{\phantom a}(x)}
$$

\bye
```

You can see that there is more space in the second line, before the parenthesis.  Maybe the phantom disables some math kerning, so this is not even possible to solve, but since I noticed it I wanted to post this "problem" anyway.  It is font specific:  for instance when no font is loaded or when the lm fonts are used I don't see any difference.

**Comment by olsak** [comment]
When we write

```
\fontfam[garamond]
$s_a$\showlists
\bye
```
then we can read in log file:
```
\mathon
\_mF 𝑠
\kern-0.58 (font)
\hbox(2.996+0.098)x4.014, shifted 2.5, direction TLT
.\_mF 𝑎
```

The \kern-.58pt (from font) is inserted here, but it is not inserted when \phantom follows (instead of a natural letter). Each character of Unicode math font can have four kerns: top-left, top-right, bottom-left, bottom-right and they are ususaly zero. But he character 𝑠 has nonzero bottom-right kern. What should be happen is not defined in classical TeX and LuaTeX insers this kern when subscript with a letter of the same font follows. But this kern is not inserted when subscrip-phantom follows. This problem is out of scope of macro level, it should be solved at engine level, IMHO.

You can correct this alligment by `... &s_{\phantom a\kern-.58pt}(x)...` but I undestand that this is not generic solution:).

**Comment by cao-** [comment]
Yes, I imagined that it was something similar to [issue #174](https://github.com/latex3/luaotfload/issues/174) or [issue #173](https://github.com/latex3/luaotfload/issues/173) of luaotfload, so something related to the luatex engine.   Anyhow, I just wanted to be sure, by making you aware of it.  Thanks for the answer :)
