### ISSUE TITLE
Ideas for extending the user base

### ISSUE THREAD

**Issue by robertbachmann** [olsak/OpTeX#32]
I'm creating this ticket as a follow-up to this [discussion](https://github.com/olsak/OpTeX/commit/48958c3ce03123cbc21a1019fc642ded6306b24b#commitcomment-45528975), so that we can collect ideas here.

**Comment by robertbachmann** [comment]
Here are some of my ideas.

### User forum

A mailing-list/forum could be useful. IMO both [Google Groups](https://groups.google.com/) or the new
[GitHub discussion feature](https://docs.github.com/en/discussions)

### Pandoc/Markdown support

People often don't write TeX directly but rather use a tool like `pandoc` to convert from
Markdown -> TeX. 

Currently `pandoc` supports LaTeX and ConTeXt as output formats. 
I'm working on a [pandoc custom lua-writer](https://pandoc.org/MANUAL.html#custom-writers) `pandoc-optex` that adds OpTeX support. 
The first version will be online in a couple of days.

### Gap analysis

I'm currently in the process of looking at various documents I've created with LaTeX to see
which features could be ported to OpTeX (the format itself or more likely an `.opm` module)

### Overleaf

Overleaf seems to be quite popular with some people. I'm currently experimenting how 
to get the Overleaf Editor to play nicely with OpTeX

**Comment by olsak** [comment]
### Ad: User forum

It is good idea. It cannot be Google forum because I have no Google account. I didn't accept the user agreement suggested by Google, so I cannot have such account (http://petr.olsak.net/zkusenost-gog.html).

It should be at GitHub. But I don't know if it is a limitation for another possible users.

The question and answers can be realized at tex.stackexchange. The tag "optex" is here but not many questions. The reason shoud be: A) OpTeX users knows everything they need (because using OpTeX is simple) or B) the set of OpTeX users is almost empty :).

### Ad: pandoc convertors

This is great suggestion. I was thinking about it too, see my document OMLS (http://petr.olsak.net/ftp/olsak/optex/omls.pdf). IMHO, authors should use Markdown (or something similar) and convert their documents to LaTeX/ConTeXt/OpTeX. If they need to use it only as "to PDF convertor" (a blackbox) then it does not matter what TeX format is used. But if Markdown is used only as a tool to pre-processing a document by authors, then the conversion to a .tex file is done, then a typesetter can add more information about conversion to PDF in the .tex file. He/she can control the processing to PDF in more detail, using macros. So, .tex file (and additional macro files) is the main source of the document where the superset of information needed for all processing of the document is present (processing to various formats, not only PDF). The .tex file should be archived for latter use and it is a "center or heard of the document". What TeX format is used does matter in this second case.

### Ad: gap analysis

I am ready to help OpTeX users if they need any additional feature. Typically, such a requirement can be solved by a few macro lines, so I add the result to the OpTeX tricks page (http://petr.olsak.net/optex/optex-tricks.html). I do this continuously, so I didn't think about a special gap analysis. Maybe, some requirements needs more than few lines of the code, then the package .opm should be created. For example, one student at our faculty will prepare an OpTeX tool for advanced PDF features (annotations, sounds, etc.). This is his bachelor's thesis topic.I hope that his result will be a .opm package.

### Ad: Overleaf

Overleaf is LaTeX oriented. One can use OpTeX here but with more effort before starting it. It is described in OpTeX trick 0022 (the last one on the www page). If it is possible to add a module which makes the Overleaf text Editor more OpTeX friendly, then this will be nice. I don't know about such possibility.

**Comment by cao-** [comment]
Comparison questions like this [TeXStackExchange](https://tex.stackexchange.com/questions/588147/why-doesnt-latex-implement-single-pass-references?noredirect=1#comment1477505_588147) may help get users interested.  Or maybe not :)

Regarding features that could be implemented in OpTeX, one that I see nowhere mentioned in OpTeX (it is mentioned in tex-nutshell) is an analogous to the LaTeX microtype package.  Of course there are the primitive luatex commands for this purpose, which I also successfully managed to use without much knowledge on what I was doing, but an easier interface would be nice.

Regarding packages, when I have time I could try and write some styles for the slides, more or less copying some of the beamer styles, if it may be useful.  Let me know.
