### ISSUE TITLE
Colors and \pdfrestore

### ISSUE THREAD

**Issue by gromadan** [olsak/OpTeX#82]
It seems that the colors in OpTeX do not work well with `\pdfsave` and `\pdfrestore`. Consider the following code

    \pdfsave\pdfrotate{90}\Red A\pdfrestore
    
    \Red B
    
    \bye

The letter B is black although it should be red.

(If I remember correctly, it was possible to turn off the color stacking in the earlier versions of OpTeX, which might help here. But I did not find this possibility in the current documentation.)

**Comment by gromadan** [comment]
Thanks for your extensive answer, but

    \pdfsave\pdfrotate{90}{\Red A}\pdfrestore

    \Red B

does not work for me either. Did you try it yourself? Maybe I am doing something wrong. I actually thought before that the grouping might be important, but nothing was really working

**Comment by gromadan** [comment]
And your suggestion works neither. Maybe there is some problem with my installation.

**Comment by vlasakm** [comment]
Hm, indeed you are right, sorry. I was testing with #74 already applied. My apologies.

Why it doesn't work without #74 is because of an optimization in the color switching - to save bytes in the PDF, color is changed only when needed, without #74 `\pdfrestore`s are not seen as color needing, so there is in fact nothing nonred between red A and red B, which means that the code thinks that red is still active when it gets to B. This is exactly what issue #73 is about and #74 is trying to solve.

@olsak Did you decide about #74? I think this is more evidence that it is probably right way to go.

**Comment by olsak** [comment]
I accepted #74. Thank you.
